import numpy as np
import matplotlib.pyplot as plt
import sys
import time

'''
Let's prove 3 things where NumPy is better than just Python data structures

1) Numpy requires less memory
2) Numpy is faster
3) Numpy is convenient

'''

N = 100000
pythonList = range(N)
# as all python list elements are objects we can calculate memory
# size of a Python list as follows (number of elements * element size)
print("Python list size = ", len(pythonList)*sys.getsizeof(1))

'''
Your task is to first create N element wide NumPy list, then
calculate and print NumPy list size. Hint. use size and itemsize attributes of 
NumPy

numpyList = ??*
print("NumPy list size = ", ???)
'''

# And now we demonstrate that NumPy is faster
# Let's multiply lists generated by themselves
start = time.time()
pythonListResult = [(x+y) for x,y in zip(pythonList,pythonList)]
print("Adding each element in a Python list took =",(time.time()-start)*1000,"ms")

'''
Your tasks are the following:
1) prove to yourself that line 33 actually does element by element addition
2) use some other Python looping function to implement python list element by element
   addition and measure its time
3) Implement NumPy list addition without for loop (as NumPy can do vector and matrix
   additions without a loop function). And measure NumPy list addition time
4) plot (with help of plt.subplot) 3 results 1) python list addition result,
   2) your own loop addition result and 3) NumPy list addition result to one figure
   and of course all 3 results should be the same
5) Explain in a comment of your python file why NumPy is convenient (mukava)

'''



